### ISSUE TITLE
sps30.h >> SER_STOP_MEASUREMENT

### ISSUE THREAD

**Issue by detamend** [paulvha/sps30#2]
Hello Paul - great library!!

I may have stumbled upon a error in sps30.h, line 291:

> bool probe();
>    bool reset() {return(Instruct(SER_RESET));}
>    bool start() {return(Instruct(SER_START_MEASUREMENT));}
>    bool stop() {return(Instruct(SER_START_MEASUREMENT));}
>    bool clean() {return(Instruct(SER_START_FAN_CLEANING));}
		
should 

bool stop() {return(Instruct(SER_**START**_MEASUREMENT));}

not be

bool stop() {return(Instruct(SER_**STOP**_MEASUREMENT));}

? Seems like a copy-error :)

**Comment by paulvha** [comment]
Good catch.. you are right.. I will make an update
Thanks
Paul

**Comment by paulvha** [comment]
change applied.

Thanks again

regards,
Paul
