### ISSUE TITLE
SPS not running Uart

### ISSUE THREAD

**Issue by tonbor** [paulvha/sps30#23]
Have purchased a new SPS30. Label 2021 03-03. Operation I2C runs well with both the original library and Pauls. In no way it will run UART. Tried on an Esp32 and mega. With external 5volt power, ground through connected. Cable 4 not connected. No power to SPS30 when changing I2C to UART, cable 4. Right serial ports named. Trying for many days but no results. Someone same problem? Some help? 
Product name  : 00080000
Firmware level: 2.2
Library level : 1.4

**Comment by tonbor** [comment]
![16339552882707860508367162316147](https://user-images.githubusercontent.com/42464290/136789973-1ca42b70-50ec-4894-838e-6d2c02945812.jpg)
Do you have a wiring diagram? Upload picture

Try to exchange TX and RX line: Of course, busy 2 days

Which example do you use to test ?  Example 12, changed and try all 3 serials, example 11 modifyed  to uart serial 1

**Comment by tonbor** [comment]
Debug (of course) 
SPS30-Example12: Basic reading with any serial channel select. press <enter> to start
Trying to connect.
Sending:  0x7E 0x00 0xD1 0x00 0x2E 0x7E
TimeOut during reading byte 0
could not probe / connect with SPS30.
Program on hold

**Comment by paulvha** [comment]
agree.. but when it does not work (yet) I normally make no assumptions and perform double / triple checks. It did provide me sometimes with an unexpected solution.

**Comment by paulvha** [comment]
wow.. AMAZING.... so there is something wrong with the sense wire /pin. Maybe the 10K was too low ( given that you measure 0 hm it might have pulled the 5V down to much). But internal there should be a pull-up (to enable to leave the line floating). Maybe try a higher value (say 1M) for pull-up. Also remove the cable from the SPS30 and measure the cable to GND (NOT connected) and measure directly on pin4 on the SPS30 tol GND to see where the short circuit is.
at least you got it to work...
regards,
Paul

**Comment by tonbor** [comment]
measure directly on pin4 on the SPS30 to GND , 4.58K ohm

**Comment by tonbor** [comment]
Gnd pin to pin 4 is 4.58 k ohm, no cable

**Comment by paulvha** [comment]
it nearly looks as if it is turned around : connect to +5V for UART communication and keep it floating for I2C. VERY weird.. maybe still try to get  a replacement..

**Comment by tonbor** [comment]
A got a full refund from seller, thanks Paul
